### ISSUE TITLE
Enquiries on dimension

### ISSUE THREAD

**Issue by pattylo** [ZJU-FAST-Lab/SDLP#2]
Hi, first of all, I would like to thank you for creating this repo, and I have only one simple question concerning the content of this library. As you have mentioned in the README file, this solver works super efficient when the preset dimension is <10. Thus, my question is that what would happen if I increase the number of the dimension, say like above 50? Thank you in advance for your time.

**Comment by ZhepeiWang** [comment]
This solver is specialized for computational geometry. As for the complexity w.r.t. dimension, please check https://github.com/ZJU-FAST-Lab/SDLP/issues/1#issuecomment-874701651
